### ISSUE TITLE
Azure Devops Release Classic - Set pipeline variables for future stages

### ISSUE THREAD

**Issue by tomwilsond1** [jessehouwing/azure-pipelines-variable-tasks#96]
I'm looking to use this plugin inside azure devops releases to pass variables down to future stages.

Will this work?

Related...
https://stackoverflow.com/questions/62128394/pass-azure-devops-release-pipelineclassic-editor-output-variable-to-multiple-j

![image](https://user-images.githubusercontent.com/111394847/201770366-f6981d42-8488-4ad1-82c4-5bcea31108ab.png)

![image](https://user-images.githubusercontent.com/111394847/201770455-0617cd7c-14ad-4095-bd27-d4456911f556.png)

**Comment by jessehouwing** [comment]
Haven't used UI based pipelines since forever.

With the setOutput option on and on the output variables tab setting the name should make the variable accessible, but I can't remember a syntax to reference that variable from a next stage/job.

In YAML this should work:

Dependencies.stagename.jobname.taskname.outputvariablename.

From memory...

**Comment by jessehouwing** [comment]
It won't indeed update the value in the release definition.
